import type { Metadata } from "next";
import { Instrument_Serif, Schoolbell } from "next/font/google";
import "./stickytheme.css";

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

const schoolBell = Schoolbell({
  variable: "--font-schoolbell",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Doni & Byan | Wedding Invitation",
  description: "Generated by create next app",
};

export default function StickyThemeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${schoolBell.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
